insert into users(idd,email,full_name,password) values(1,'test@test.com','test','test')   ;
insert into users(idd,email,full_name,password) values(2,'123@gmaiil.com','Kiskutya','123')   ;
insert into roles(role) values ('user')                                        ;
insert into roles(role) values ('admin')                                       ;
insert into users_roles(user_id, role_id) values (1,1);
insert into users_roles(user_id, role_id) values (2,2);



insert into news(title,content,date) values('Változik a vonatközlekedés rendje a kegyeleti ünnepek idején','A hosszú hétvége előtt a MÁV azt javasolja, hogy néhány nappal az ünnep előtt, előre vegyék meg az utasok a menetjegyeket. Ilyenkor rengetegen mennek a temetőkbe vagy látogatnak el a rokonaikhoz, ezért csúcsforgalom várható a pályaudvarokon, és néhány nap alatt akár félmillióan is útra kelhetnek a vonatokkal. Sokan utazhatnak már csütörtökön is, de legtöbben vasárnap szállnak majd vonatra, mert aznap ér véget az őszi szünet. A tavalyi négynapos ünnep utolsó napján – részben az őszi szünet vége miatt – megduplázódott az utasforgalom egy átlagos vasárnaphoz képest. A felkészülés és a megnövelt kapacitás ellenére – egyes népszerűbb utazási időpontokban – gyorsan megtelhetnek az InterCity vonatok. A vasúttársaság az IC vonatokhoz a helyfoglalások figyelembevételével – a lehetőségekhez mérten – plusz kocsikat kapcsol. Az InterCity vonatokon kívül a gyors-, sebes-, illetve személyvonatokat is választhatják az utasok. November 3-án, vasárnap közlekedik Nyíregyházáról Debrecenen át a Nyugati pályaudvarra a tavaly bevezetett és gyorsan népszerűvé vált Televonat.
A pénztárak előtti sorban állás elkerülése érdekében az utasok a vasúttársaság internetes jegyvásárlási rendszerében vagy az okostelefonokon elérhető MÁV applikációban gyorsan és egyszerűen megválthatják a menetjegyeket és helyjegyeket. Az online vagy mobilalkalmazással megvett e-vonatjegyek a pénztári árhoz képest 10 százalékkal olcsóbbak, míg a menetrendi keresőben @ jellel jelölt, csúcsidőn kívüli vonatokra legalább 100 kilométer távolságra váltott e-vonatjegyekre 20 százalékos engedmény jár. Az automatáknál vásárlók 5 százalékos kedvezményt kapnak.','2019-11-22 10:12')
;insert into news(title,content,date) values('Korlátozások a Nyugati pályaudvar pénztárcsarnokában','A Nyugati pályaudvar pénztárcsarnokában a teljes belső felületet takaró védőtetőt építenek október 17-től a tetőszerkezet felújításának előkészületeként, hogy a jövőre kezdődő munkálatok idején is zavartalanul és biztonságosan használhassák az utasok a fogadóteret.
Október 14-étől kezdik el az állványzathoz szükséges anyagok kiszállítását, ez még nem érinti az utasáramlási útvonalakat a csarnokban. A korlátozásokkal járó állványépítés október 17-én kezdődik. A november 4-ig tartó első ütemben a pénztárcsarnokban az első hat ablak működik; csak a ceglédi folyosó (gyorsétterem felőli bejárat) és a vágánycsarnok felől lesz megközelíthető. Ezzel egy időben a szomszédos Márványcsarnokban, a peron felőli üvegfal üvegezését és festését is elkezdik.
November 5-8-ig a terem közepén zárnak le egy részt, ebben az időszakban a ceglédi folyosó, a vágánycsarnok és a külső vágányok (14-17. vágány) felől is lehetséges az átjárás. A 3-6-os pénztárfülkék előtti terület lesz lezárva.
November 11-18-ig csak a külső vágányok és az Eiffel tér felőli bejáraton lehet a 5-9-es pénztárablakokat elérni. Ezt követően még kiegészítő munkákat végeznek december közepéig. A védőtető elkészülte után a pénztárcsarnokba ismét a megszokott irányokból juthatnak be az utasok.
Az állványépítés idején – és terveink szerint, a jövőre kezdődő tetőfelújítás ideje alatt is – a pénztárak egy része folyamatosan és biztonságosan megközelíthető marad, a csarnok mindennap 6 órától 19:30-ig tart nyitva. Az állványozást munkanapokon a nyitvatartási időn kívül fogják végezni. A korlátozásokat és az utasok számára a közlekedési útvonalakat szalagokkal, kordonokkal és táblákkal is jelölik.','2019-11-01 19:43')
;insert into news(title,content,date) values('Megújultak a miskolci Tiszai pályaudvar peronjai','Miskolc, 2019. október 30. – Befejeződött a miskolci Tiszai pályaudvar peronjainak felújítása. A MÁV október 31-én adja át az utazóközönségnek az idei, utolsó ütemben elkészült, 2-es és 3-as vágány közötti peront.
A vasúttársaság az 1960-as években épült betonszerkezetű perontetőket 2016-tól kezdte felújítani. Legelőször a „D” perontető készült el 2016-ban, ezt követte  a „C” peron 2017-ben, idén pedig a MÁV „50 megújuló állomás” elnevezésű felújítási és karbantartási programjában a „B” perontetőt is renoválták; október 31-től, csütörtöktől vehetik birtokba az utasok.','2019-10-27 19:30')
;insert into news(title,content,date) values('aaaaaaa','cwdwqqwdqdqw','2018-01-01 12:00')
;insert into news(title,content,date) values('Új családi váró Debrecen állomáson','Egyre többen használják a szeptemberben megnyílt családi várót a debreceni állomáson. A gyermekkel utazók nagy örömére az új helyiségben játszósarok mellett gyermekmosdó és pelenkázó is kiépült.
Debrecen állomáson szeptember óta várja a legfiatalabb utasokat is a családi váróterem, amely a kisgyerekes családok utazási komfortját növeli. Az eddigi visszajelzések, a családi váróban elhelyezett vendégkönyv alapján rendkívül pozitívak, az utazóközönség nagy örömmel használja is a létesítményt. Az ötletet elsődlegesen a nyíregyházi vasútállomáson már évek óta működő családi váró sikere adta.','2019-05-03 17:00')
;insert into news(title,content,date) values('Forgalomba állt az első felújított Talent Győr és Bécs között','A MÁV-START által üzemeltetett tíz Bombardier Talent motorvonat szervizelése és annak hosszú távú megoldása a vasúttársaság számára kiemelten fontos. Ezért első lépésként, idén áprilisban a MÁV-START, a MÁV Vagon és az ÖBB két évre szóló szerződést kötött, hogy a Győr és Bécs közötti eurégiós közlekedésben használt Talentek nagyjavítása, konstrukciós hibáinak megszűntetése, valamint gazdaságos és hatékony fenntartása mielőbb rendeződjön. Jövő év végére fejeződhet be a flotta megújítása, utána már a jelenleginél megbízhatóbban, akár 80-90 százalékos üzemkészséggel közlekedhetnek.','2019-08-01 10:00')
;insert into tickets(fromm, too,date,departure,arrival,price) values ('Szeged','Nyugati','2019-08-01','13:00','14:30',1000)
;insert into tickets(fromm, too,date,departure,arrival,price) values ('Győr','Keleti','2019-04-01','13:00','14:30',1100)
;insert into tickets(fromm, too,date,departure,arrival,price) values ('Keleti','Győr','2019-11-05','13:00','14:30',900)
;insert into tickets(fromm, too,date,departure,arrival,price) values ('Szeged','Nyugati','2019-08-09','13:00','14:30',1000)
;insert into tickets(fromm, too,date,departure,arrival,price) values ('Szeged','Nyugati','2019-03-11','13:00','14:30',1000)
;insert into tickets(fromm, too,date,departure,arrival,price) values ('Szeged','Nyugati','2019-04-22','13:00','14:30',1000)


